db:
  #Если не будет передано значение username.value, то будет подставлено дефолтное (после двоеточия)
  username: ${username.value:postgres}
  password: postgres
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

spring.profiles.active: qa

# Подключение различных уровней логирования.
# В данном примере для всех логеров будут выводиться только сообщения WARN типа,
# а для ConnectionPool - INFO.
# Также можно указать только имя пакета. И логирование будет применяться для всех классов в пакете.
logging:
  level:
    root: WARN
    org.example.spring.database.pool.ConnectionPool: INFO
  # Запись логов в файл
  file:
    name: spring-starter.log
    path: /